name: release pr
on:
  push:
    branches: main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Get commit inf
        id: commit_info
        run: |
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "url=https://github.com/${GITHUB_REPOSITORY}/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Generate test report
        id: test_report
        run: |
          TITLE="Test Results ([${{ steps.commit_info.outputs.hash }}](${{ steps.commit_info.outputs.url }}))"

          echo "comment<<EOF" >> $GITHUB_OUTPUT
          cat ./reports/ava.json | node ./.github/scripts/generate-report.js --title "${TITLE}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on Release PR
        if: steps.release.outputs.pr != ''
        uses: actions/github-script@v8
        with:
          script: |
            const comment = `${{ steps.test_report.outputs.comment }}`;
            const prNumber = ${{ fromJSON(steps.release.outputs.pr).number }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment,
            });
