name: release pr
on:
  push:
    branches: main
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Tap Content
        id: tap
        run: |
          echo "tap<<EOF" >> $GITHUB_OUTPUT
          cat ./reports/ava.tap >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on Release PR
        if: steps.release.outputs.pr != ''
        uses: actions/github-script@v8
        with:
          script: |
            const tap = `${{ steps.tap.outputs.tap }}`;
            const prNumber = ${{ steps.release.outputs.pr }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: tap,
            });